In [6]:
import numpy
# world_alcohol = numpy.genfromtxt("m.csv",delimiter=",",dtype=str)
# print(type(world_alcohol))
# print(world_alcohol)
# print(help(numpy.genformtxt))

print(help(numpy()))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [16]:
# 构造数组

# 一维数组
vector = numpy.array([5,10,15,20])
# 二维数组，注意有两个括号
matrix = numpy.array([[5,10,15],[20,25,30],[35,40,45]])

print(vector)
print(matrix)

print(vector.shape) # 一维数组/每行4个元素
print(matrix.shape) # 三行三列

[ 5 10 15 20]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
(4,)
(3, 3)


In [29]:
##############
#####是否正确?
##############
third = numpy.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(third)
print(third.shape)
print(third.ndim)
##########
#3*2*2的矩阵？？？

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)
3


In [28]:
#############
####是否正确?
############
third0 = numpy.array([[[1,2],[3,4],[5,6]]])
print(third0)
print(third0.shape)
print(third0.ndim)
##########
#1*3*2的矩阵
#########

[[[1 2]
  [3 4]
  [5 6]]]
(1, 3, 2)
3


In [18]:
v = numpy.array(["1","2","3"])
print(v.dtype)
print(v)
v = v.astype(float)
print(v.dtype)
print(v)

<U1
['1' '2' '3']
float64
[1. 2. 3.]


In [20]:
print(help(numpy.array))

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [21]:
m = numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
m.sum(axis=1)

array([ 30,  75, 120])

In [22]:
m = numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])
m.sum(axis=0)

array([60, 75, 90])

In [11]:
import numpy as np
print(np.arange(15))
a = np.arange(15).reshape(3,5)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
print(a.ndim)

2


In [31]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [2]:
np.ones((2,3,4),dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [4]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [10]:
np.arange(10,30,5).reshape(2,2)

array([[10, 15],
       [20, 25]])

In [12]:
np.random.random((2,3)) # 第一个random是调用模块，第二个是调用函数，(2,3)是构造一个2*3的矩阵


array([[0.05134094, 0.63073588, 0.14218974],
       [0.86727903, 0.95890848, 0.39738407]])

In [16]:
from numpy import pi
np.linspace(0,2*pi,100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [20]:
np.linspace(2,3,5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [22]:
import numpy as np
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)
print("a - b " , a - b)
print("a - b - 1 :" , a - b - 1)
print("b**2" , b**2)
print("a < 35" , a < 35)

[20 30 40 50]
[0 1 2 3]
a - b  [20 29 38 47]
a - b - 1 : [19 28 37 46]
b**2 [0 1 4 9]
a < 35 [ True  True False False]


In [26]:
A = np.array([
    [1,1],
    [0,1]
])

B = np.array([
    [2,0],
    [3,4]
])

print('------A-------')

print(A)

print('------B-------')

print(B)

print('------A*B-------')

print(A*B)

print('------A.dot(B)-------')

print(A.dot(B))

print('------np.dot(A,B)-------')

print(np.dot(A,B))

------A-------
[[1 1]
 [0 1]]
------B-------
[[2 0]
 [3 4]]
------A*B-------
[[2 0]
 [0 4]]
------A.dot(B)-------
[[5 4]
 [3 4]]
------np.dot(A,B)-------
[[5 4]
 [3 4]]


In [27]:
import numpy as np
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [40]:
import numpy as np
a = np.floor(10*np.random.random((3,4))) # np.floor() //向下取整
print(a)
print('-------------')
print(a.ravel()) #把矩阵拉长向量
print('-------------')
a.shape = (3,-1)
# a.shape = (3,-1)
# -1帮你自动计算后一个维度的个数
print(a)
print('-------------')
print(a.T) # 矩阵转置

[[7. 3. 4. 2.]
 [9. 8. 6. 2.]
 [0. 2. 3. 5.]]
-------------
[7. 3. 4. 2. 9. 8. 6. 2. 0. 2. 3. 5.]
-------------
[[7. 3. 4. 2.]
 [9. 8. 6. 2.]
 [0. 2. 3. 5.]]
-------------
[[7. 9. 0.]
 [3. 8. 2.]
 [4. 6. 3.]
 [2. 2. 5.]]


In [48]:
# 矩阵拼接
import numpy as np
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print('----------a-----------')
print(a)
print('----------b-----------')
print(b)
print('----------------------')
print(np.hstack((a,b))) # 按行拼接
print('----------------------')
print(np.vstack((a,b))) # 按列拼接

----------a-----------
[[2. 0.]
 [9. 7.]]
----------b-----------
[[2. 0.]
 [6. 9.]]
----------------------
[[2. 0. 2. 0.]
 [9. 7. 6. 9.]]
----------------------
[[2. 0.]
 [9. 7.]
 [2. 0.]
 [6. 9.]]


In [52]:
#数据分割
a = np.floor(10*np.random.random((2,12)))
print(a)
print('------------')
print(np.hsplit(a,3))  # 按行切分，3切分成3份，得到三个array值
print('------------')
print(np.hsplit(a,(3,4))) 
# split a after  the third and the fourth cloumn
# 在第三行和第四行后进行切割
print('------------')
a = np.floor(10*np.random.random((12,2)))
print(a)
print('-------------')
np.vsplit(a,3)  # 按列切分


[[4. 3. 3. 3. 7. 5. 7. 4. 6. 4. 6. 8.]
 [9. 9. 4. 8. 0. 4. 3. 5. 1. 9. 4. 4.]]
------------
[array([[4., 3., 3., 3.],
       [9., 9., 4., 8.]]), array([[7., 5., 7., 4.],
       [0., 4., 3., 5.]]), array([[6., 4., 6., 8.],
       [1., 9., 4., 4.]])]
------------
[array([[4., 3., 3.],
       [9., 9., 4.]]), array([[3.],
       [8.]]), array([[7., 5., 7., 4., 6., 4., 6., 8.],
       [0., 4., 3., 5., 1., 9., 4., 4.]])]
------------
[[8. 2.]
 [3. 9.]
 [3. 5.]
 [5. 0.]
 [4. 3.]
 [2. 3.]
 [0. 2.]
 [5. 7.]
 [5. 5.]
 [7. 9.]
 [3. 8.]
 [0. 0.]]
-------------


[array([[8., 2.],
        [3., 9.],
        [3., 5.],
        [5., 0.]]), array([[4., 3.],
        [2., 3.],
        [0., 2.],
        [5., 7.]]), array([[5., 5.],
        [7., 9.],
        [3., 8.],
        [0., 0.]])]

In [53]:
import numpy as np
a = np.arange(12)
################
b = a # 非复制
################
# a and b are two names for the same ndarray object
print(b is a)
b.shape = (3,4)
print(a.shape)
print(id(a))
print(id(b))

True
(3, 4)
2540538182992
2540538182992


In [58]:
# 复制/有俩种方法

# 浅复制
c = a.view() # 浅复制，共用一套值
print(c is a)
c.shape = (2,6)
print('a.shape: ' ,a.shape)
print('c.shape: ' ,c.shape)
c[0,4] = 1234    # a 的值也变量，a和c共用了一套值
print(a)
print(id(a))
print(id(c))

False
a.shape:  (3, 4)
c.shape:  (2, 6)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
2540538182992
2540538442256


In [59]:
# 深复制
d = a.copy()
print(d is a)
d[0,0] = 9999
print('------d-------')
print(d)
print('------a-------')
print(a)

False
------d-------
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
------a-------
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [60]:
#索引
import numpy as np
data = np.sin(np.arange(20).reshape(5,4))
print(data)
ind = data.argmax(axis = 0) # 按列来进行计算
print(ind) # 输出每一列的最大值所在的行（以0开始），索引
data_max = data[ind,range(data.shape[1])] 
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [62]:
# 扩展
import numpy as np
a = np.arange(0,40,10)
print(a)
b = np.tile(a,(3,5)) #构造一个三行五列的二维数组，每一个元素都是a
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


In [76]:
#排序
import numpy as np
a = np.array([[4,3,5],
             [1,6,1],
             [0,2,3]])
print(a)
print('------按列排序-------')
b = np.sort(a,axis = 0) #对二维数组排序,0为按列排序，1为按行排序
print(b)
#b
a.sort(axis = 1)
print('--------按行排序-----') #对二维数组排序,0为按列排序，1为按行排序
print(a)

print('################')
a = np.array([5,3,1,2])
j = np.argsort(a)   # 索引，求最小值索引（编号）

print('-------最小值索引------')
print(j)
print('-------排序结果------')
print(a[j])   # 排序完之后的结果

[[4 3 5]
 [1 6 1]
 [0 2 3]]
------按列排序-------
[[0 2 1]
 [1 3 3]
 [4 6 5]]
--------按行排序-----
[[3 4 5]
 [1 1 6]
 [0 2 3]]
################
-------最小值索引------
[2 3 1 0]
-------排序结果------
[1 2 3 5]
